import Link from 'next/link';
import { NewsNav } from '@/components/news/news-nav';

export default function AttributionPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <NewsNav activeRegion="global" activePeriod="daily" />

      <main className="flex-1 px-6 py-8">
        <div className="max-w-3xl mx-auto">

          <div className="mb-8">
            <p className="label-xs text-accent-info">Source Attribution</p>
            <h1 className="mt-2 text-3xl font-light tracking-tight text-foreground">
              Attribution Policy
            </h1>
            <p className="body-lg mt-4 max-w-xl">
              BuildAtlas aggregates, paraphrases, and cites news sources to produce startup intelligence.
              We never reproduce full articles. All original reporting belongs to its publishers.
            </p>
          </div>

          <div className="space-y-12">
            <section>
              <h2 className="headline-md mb-4">How we use sources</h2>
              <p className="body-md mb-4">
                BuildAtlas ingests headlines and metadata from public RSS feeds, press releases, and
                news APIs. Our AI editor paraphrases stories into structured intelligence briefs.
                We do not copy or host full article text. Every item links back to the original
                publisher so readers can access the full context at the source.
              </p>
              <p className="body-md">
                Summaries are original paraphrases generated by our pipeline. No sentence in a
                BuildAtlas brief should match more than eight consecutive words from any source article.
              </p>
            </section>

            <section>
              <h2 className="headline-md mb-4">Citation policy</h2>
              <p className="body-md mb-4">
                Every news cluster on BuildAtlas includes:
              </p>
              <ul className="space-y-2 body-sm mb-6">
                <li className="flex items-start gap-2">
                  <span className="text-accent-info">&bull;</span>
                  <span>Publisher name and publication date for each source</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-accent-info">&bull;</span>
                  <span>Direct outbound link to the original article</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-accent-info">&bull;</span>
                  <span>Paywall indicator when applicable</span>
                </li>
              </ul>
              <p className="body-md">
                We do not gate or intercept outbound clicks. All source links open directly
                in the publisher&apos;s site.
              </p>
            </section>

            <section>
              <h2 className="headline-md mb-4">Takedown requests</h2>
              <p className="body-md">
                If you are a publisher and would like content referencing your work to be
                removed or corrected, please email{' '}
                <a
                  href="mailto:support@graph-atlas.com"
                  className="text-accent-info hover:text-foreground transition-colors"
                >
                  support@graph-atlas.com
                </a>{' '}
                with the specific URL and the nature of your request. We aim to respond within
                two business days.
              </p>
            </section>
          </div>

          <div className="mt-16 p-6 rounded-2xl border border-border/40 bg-card/60 text-center">
            <p className="body-md mb-4">
              Learn more about how we process and score news.
            </p>
            <Link
              href="/methodology"
              className="inline-flex items-center gap-2 px-6 py-2.5 text-sm font-medium bg-accent text-accent-foreground rounded hover:bg-accent/90 transition-colors"
            >
              Read Methodology
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
